source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FLCommonLibrary_Example', :exclusive => true do
  pod "FLCommonLibrary", :path => "../"
end

target 'FLCommonLibrary_Tests', :exclusive => true do
  pod "FLCommonLibrary", :path => "../"

  
end
